name: Test Secrets Exposure

on:  
  workflow_dispatch:  # Allows manual triggering  

jobs:
  test-secrets:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Print Environment Variables
        run: env | sort  # List all environment variables

      - name: Echo a Secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"  

      - name: Try to Write Secret to a File
        run: |
          echo "SECRET=${{ secrets.MY_SECRET }}" > secret.txt
          cat secret.txt
